<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="2_Notebook.xsl"?>
<!DOCTYPE produtos [
    <!ELEMENT produtos (produto+)>
    <!ELEMENT produto (nome,descricao,preco,imagem,tipo,marca)>
    <!ELEMENT nome (#PCDATA)>
    <!ELEMENT descricao (#PCDATA)>
    <!ELEMENT preco (#PCDATA)>
    <!ELEMENT imagem (#PCDATA)>
    <!ELEMENT tipo (#PCDATA)>
    <!ELEMENT marca (#PCDATA)>
]>
<produtos>
    <produto>
        <nome>Notebook Acer Aspire 3 A315-56-35ET</nome>
        <descricao>Notebook Acer Aspire 3 A315-56-35ET 10ª Intel Core i3 8GB 512GB SSD W10 15,6''</descricao>
        <preco>3199.99</preco>
        <imagem>n1.jpg</imagem>
        <tipo>notebook</tipo>
        <marca>Acer</marca>
    </produto>
    <produto>
        <nome>Notebook Lenovo Ideapad S145</nome>
        <descricao>Notebook Ultrafino Lenovo Ideapad S145 Intel Core i3-8130U 8GB 1TB 15.6" Teclado ABNT 2</descricao>
        <preco>2759.99</preco>
        <imagem>n2.jpg</imagem>
        <tipo>notebook</tipo>
        <marca>Lenovo</marca>
    </produto>
    <produto>
        <nome>Notebook Gamer 2AM E550</nome>
        <descricao>Notebook Gamer 2AM E550 Intel Core I7 8GB 256GB SSD IPS Full HD 15,6" Teclado ABNT2</descricao>
        <preco>5599.99</preco>
        <imagem>n3.jpg</imagem>
        <tipo>notebook</tipo>
        <marca>2AM</marca>
    </produto>
    <produto>
        <nome>Notebook Positivo Motion Q464B</nome>
        <descricao>Notebook Positivo Motion Q464B Intel Atom Quad core 4GB 64GB SSD+64GB Nuvem 14" W10</descricao>
        <preco>1449.99</preco>
        <imagem>n4.jpg</imagem>
        <tipo>notebook</tipo>
        <marca>Positivo</marca>
    </produto>
    <produto>
        <nome>Notebook Compaq Presario CQ-25</nome>
        <descricao>Notebook Compaq Presario CQ-25 Intel Pentium 4GB 120GB SSD Tela 15" Full Led </descricao>
        <preco>1599.99</preco>
        <imagem>n5.jpg</imagem>
        <tipo>notebook</tipo>
        <marca>Compaq</marca>
    </produto>
<!--NOVOS-->
    <produto>
        <nome>Notebook Positivo Motion Q432B</nome>
        <descricao>Notebook Positivo Motion Q432B 4GB 320GB SSD + 64GB Tela 14" Full Led Windows 10</descricao>
        <preco>1359.99</preco>
        <imagem>n6.jpg</imagem>
        <tipo>notebook</tipo>
        <marca>Positivo</marca>
    </produto>
    <produto>
        <nome>Halashop Student Android Laptop</nome>
        <descricao>Halashop-10.1 Inch 1GB ram de 8 gb rom A33 Notebook cpu Windows 10 Student Android Laptop</descricao>
        <preco>950.99</preco>
        <imagem>n7.jpg</imagem>
        <tipo>notebook</tipo>
        <marca>Halashop</marca>
    </produto>
    <produto>
        <nome>Notebook Samsung Book E20</nome>
        <descricao>Notebook Samsung Book E20 Intel Celeron 4GB 500GB W10 15,6", Teclado ABNT 2 - Prata</descricao>
        <preco>2230.99</preco>
        <imagem>n8.jpg</imagem>
        <tipo>notebook</tipo>
        <marca>Samsung</marca>
    </produto>
    <produto>
        <nome>Notebook Samsung np530xbb-ad3</nome>
        <descricao>Notebook 13.3” flash f30 celeron/n4000/4gb/64gb/win10 aquarela - np530xbb-ad3 samsung</descricao>
        <preco>2695.00</preco>
        <imagem>n9.jpg</imagem>
        <tipo>notebook</tipo>
        <marca>Samsung</marca>
    </produto>
    <produto>
        <nome>Notebook 2 em 1 Positivo Duo C4128A-1</nome>
        <descricao>Notebook 2 em 1 Positivo Duo C4128A-1 - Intel Celeron 4GB 128GB eMMC Touch Screen 11,6”</descricao>
        <preco>1899.00</preco>
        <imagem>n10.jpg</imagem>
        <tipo>notebook</tipo>
        <marca>Positivo</marca>
    </produto>
    <produto>
        <nome>Notebook Lenovo S145 Core i3</nome>
        <descricao>Notebook Lenovo S145 Core i3 8130U 4GB RAM 1TB Linux Tela 15,6'' 81XMS00000</descricao>
        <preco>2510.00</preco>
        <imagem>n11.jpg</imagem>
        <tipo>notebook</tipo>
        <marca>Lg</marca>
    </produto>
    <produto>
        <nome>Notebook Samsung Book E30</nome>
        <descricao>Notebook Samsung Book E30 Intel Core i3 4GB 1TB - 15,6” Full HD Windows 10, Teclado ABNT 2</descricao>
        <preco>2849.00</preco>
        <imagem>n12.jpg</imagem>
        <tipo>notebook</tipo>
        <marca>Samsung</marca>
    </produto>
    <produto>
        <nome>Notebook Ultra-fino laptop</nome>
        <descricao>Ultra-fino laptop pc de 14,1 polegadas Netbook 1366 * 768p pixéis 2GB + 32GB</descricao>
        <preco>2849.00</preco>
        <imagem>n13.jpg</imagem>
        <tipo>notebook</tipo>
        <marca>Coolstyle</marca>
    </produto>
    <produto>
        <nome>Chromebook Acer CB5-132T-C5MD</nome>
        <descricao>Chromebook Acer CB5-132T-C5MD Intel Celeron N3160 4GB 32GB eMMC 11,6" Chrome OS</descricao>
        <preco>2849.00</preco>
        <imagem>n14.jpg</imagem>
        <tipo>notebook</tipo>
        <marca>Acer</marca>
    </produto>
    <produto>
        <nome>Notebook Positivo Motion Intel</nome>
        <descricao>Notebook Positivo Motion Intel Atom Q464B 4GB 64GB SSD 14" Windows 10 Cinza</descricao>
        <preco>1487.00</preco>
        <imagem>n14.jpg</imagem>
        <tipo>notebook</tipo>
        <marca>Positivo</marca>
    </produto>
    <produto>
        <nome>Notebook Asus ZenBook UX431FA-AN203T</nome>
        <descricao>Notebook Asus ZenBook UX431FA-AN203T / CORE i7 / 8GB, / 256GB SSD / Windows 10 Home </descricao>
        <preco>5799.00</preco>
        <imagem>n15.jpg</imagem>
        <tipo>notebook</tipo>
        <marca>Apple</marca>
    </produto>
    <produto>
        <nome>Notebook Dell Inspiron 15 3000</nome>
        <descricao>Notebook Dell Inspiron 15 3000 i15-3583-D05P - Intel Pentium Gold 4GB 500GB 15,6” Linux</descricao>
        <preco>2379.00</preco>
        <imagem>n16.jpg</imagem>
        <tipo>notebook</tipo>
        <marca>Dell</marca>
    </produto>
</produtos>