<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE produtos [
    <!ELEMENT produtos (produto+)>
    <!ELEMENT produto (nome,descricao,preco,imagem,tipo,marca)>
    <!ELEMENT nome (#PCDATA)>
    <!ELEMENT descricao (#PCDATA)>
    <!ELEMENT preco (#PCDATA)>
    <!ELEMENT imagem (#PCDATA)>
    <!ELEMENT tipo (#PCDATA)>
    <!ELEMENT marca (#PCDATA)>
]>
<produtos>
    <produto>
        <nome>Tablet Samsung Galaxy A7</nome>
        <descricao>Tablet Samsung Galaxy A7 64GB Wi-Fi 4G Tela 10.4" - Octa-Core 2.0GHz - Grafite</descricao>
        <preco>1439.10</preco>
        <imagem>GalaxyA7.jpg</imagem>
        <tipo>tablet</tipo>
        <marca>Samsung</marca>
    </produto>
    <produto>
        <nome>Tablet Positivo Twist Tab T770B</nome>
        <descricao>Tablet Positivo Twist Tab T770B 32GB Wi-Fi Tela 7" Android QuadCore de 1,5 GHz - Cinza Escuro</descricao>
        <preco>399.00</preco>
        <imagem>PositivoTwistTab.jpg</imagem>
        <tipo>tablet</tipo>
        <marca>Positivo</marca>
    </produto>
    <produto>
        <nome>Tablet Ptb7qsg 3g Philco</nome>
        <descricao>Tablet Ptb7qsg 3g Philco, Android 8.1 E Tela Multi-toque</descricao>
        <preco>449.99</preco>
        <imagem>TabletPtb7qsg.jpg</imagem>
        <tipo>tablet</tipo>
        <marca>Philco</marca>
    </produto>
    <produto>
        <nome>Tablet Multilaser M7 3G Plus NB304</nome>
        <descricao>Tablet Multilaser M7 3G Plus NB304,Preto,Tela 7,Dual Chip,Wi-fi+3G,Bluetooth,Câm traseira 2MP e 16GB</descricao>
        <preco>494.10</preco>
        <imagem>MultilaserM7.jpg</imagem>
        <tipo>tablet</tipo>
        <marca>Multilaser</marca>
    </produto>
    <produto>
        <nome>Tablet Samsung Galaxy Tab S5e</nome>
        <descricao>Tablet Samsung Galaxy Tab S5e 64GB Wi-Fi 4G Tela 10.5" Android Octa-Core 2.0GHz - Prata</descricao>
        <preco>2499.00</preco>
        <imagem>GalaxyTabS5e.jpg</imagem>
        <tipo>tablet</tipo>
        <marca>Samsung</marca>
    </produto>
</produtos>